"""reboot tables

Revision ID: 298afeb4e7bf
Revises: 
Create Date: 2025-01-29 17:39:16.821569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '298afeb4e7bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('date_entered', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.Column('billing_address_city', sa.String(length=100), nullable=True),
    sa.Column('phone_office', sa.String(length=50), nullable=True),
    sa.Column('RUC_code', sa.String(length=11), nullable=False),
    sa.Column('shipping_address_street', sa.String(length=255), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('RUC_code')
    )
    op.create_table('odt_number_counter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('date_entered', sa.DateTime(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('birthdate', sa.DateTime(), nullable=True),
    sa.Column('phone_mobile', sa.String(length=20), nullable=True),
    sa.Column('phone_work', sa.String(length=20), nullable=True),
    sa.Column('email1', sa.String(length=100), nullable=False),
    sa.Column('primary_address_street', sa.String(length=255), nullable=True),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('odts',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('odt_number', sa.Integer(), nullable=False),
    sa.Column('date_entered', sa.DateTime(), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('delivery_type', sa.String(length=50), nullable=True),
    sa.Column('delivery_address', sa.String(length=255), nullable=True),
    sa.Column('delivery_contact', sa.String(length=100), nullable=True),
    sa.Column('delivery_phone', sa.String(length=20), nullable=True),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('delivery_obs', sa.Text(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('account_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('contact_id', mysql.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('odt_number')
    )
    op.create_table('file_attachments',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.Enum('COST_BUDGET', 'PURCHASE_COMPLIANCE', 'REFERENCE_IMAGE', name='filetype'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('odt_id', mysql.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['odt_id'], ['odts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_attachments')
    op.drop_table('odts')
    op.drop_table('contacts')
    op.drop_table('odt_number_counter')
    op.drop_table('accounts')
    # ### end Alembic commands ###
