"""Initial migration for shared models

Revision ID: b0546c677c7a
Revises: 
Create Date: 2025-01-21 02:45:06.506100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0546c677c7a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.Column('billing_address_city', sa.String(length=100), nullable=True),
    sa.Column('phone_office', sa.String(length=20), nullable=True),
    sa.Column('RUC_code', sa.String(length=20), nullable=False),
    sa.Column('shipping_address_street', sa.String(length=255), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('RUC_code')
    )
    op.create_table('contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('date_entered', sa.DateTime(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('birthdate', sa.DateTime(), nullable=True),
    sa.Column('phone_mobile', sa.String(length=20), nullable=True),
    sa.Column('phone_work', sa.String(length=20), nullable=True),
    sa.Column('email1', sa.String(length=100), nullable=False),
    sa.Column('primary_address_street', sa.String(length=255), nullable=True),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
