"""Añadir modelo FileAttachment y actualizar ODT

Revision ID: e8a0e3f663eb
Revises: b0546c677c7a
Create Date: 2025-01-29 17:15:47.265978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e8a0e3f663eb'
down_revision: Union[str, None] = 'b0546c677c7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('odts',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('date_entered', sa.DateTime(), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('delivery_type', sa.String(length=50), nullable=True),
    sa.Column('delivery_address', sa.String(length=255), nullable=True),
    sa.Column('delivery_contact', sa.String(length=100), nullable=True),
    sa.Column('delivery_phone', sa.String(length=20), nullable=True),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('delivery_obs', sa.Text(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('account_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('contact_id', mysql.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_attachments',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.Enum('COST_BUDGET', 'PURCHASE_COMPLIANCE', 'REFERENCE_IMAGE', name='filetype'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('odt_id', mysql.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['odt_id'], ['odts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('accounts', 'id',
               existing_type=mysql.VARCHAR(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('accounts', 'phone_office',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('accounts', 'RUC_code',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=11),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'RUC_code',
               existing_type=sa.String(length=11),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('accounts', 'phone_office',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('accounts', 'id',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_table('file_attachments')
    op.drop_table('odts')
    # ### end Alembic commands ###
